### ISSUE TITLE
Gradient Outlines Glitched

### ISSUE THREAD

**Issue by GrahamSH-LLK** [LLK/scratch-render#635] opened 2020-06-05 14:28 UTC
### Expected Behavior

Gradient outlines should look the same unless you change them. Also, they should look the same in the stage as they do in the paint editor.
### Actual Behavior

Sometimes, moving a shape will change what a gradient looks like. Also, the stage doesn't always match the colors of the paint editor.
### Steps to Reproduce
See [this](https://scratch.mit.edu/projects/402177554/editor/) project. Go to the paint editor. Drag the circle off of the pointy thing. Watch the stage change.  Also, see that the stage doesn't match the paint editor.

### Operating System and Browser
Chrome OS Chrome

**Comment by adroitwhiz** [comment] 2020-06-05 14:53
This is a duplicate of https://github.com/LLK/scratch-svg-renderer/issues/142 which I specifically made that test project for. https://github.com/LLK/scratch-svg-renderer/pull/143 fixed it.

**Closed as completed by adroitwhiz** 2020-06-05 14:53 UTC

**Comment by GrahamSH-LLK** [comment] 2020-06-05 19:50
@adroitwhiz That issue doesn't explain the changing of the gradients when moved. Is that fixed by  LLK/scratch-svg-renderer#143?

**Comment by adroitwhiz** [comment] 2020-06-05 19:53
Yes.
