### ISSUE TITLE
Ugly dark fringe around resampled costume's edges

### ISSUE THREAD

**Issue by adroitwhiz** [LLK/scratch-render#459] opened 2019-05-22 04:47 UTC
### Expected Behavior

Alpha blending should work properly.

### Actual Behavior

An alpha-multiplication-related dark fringe appears around costumes whose textures are linearly resampled, as seen in [this project](https://scratch.mit.edu/projects/311778332/):
![image](https://user-images.githubusercontent.com/25993062/58147987-eb51fb80-7c2a-11e9-9e12-8cb24a86804f.png)

I believe the underlying problem is discussed in the article [GPUs prefer premultiplication](http://www.realtimerendering.com/blog/gpus-prefer-premultiplication/)--canvas image data is not premultiplied, and must be premultiplied before being sampled.

### Steps to Reproduce

1. Create a project
2. Draw a vector costume in a bright color
3. Rotate the sprite

**Comment by fsih** [comment] 2019-06-13 17:03
Dupe of https://github.com/LLK/scratch-render/issues/237

**Closed** 2019-10-13 16:34 UTC
Labels: bug, needs discussion
