### ISSUE TITLE
Pen line thickness changes depending on the length

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-render#599] opened 2020-05-08 05:16 UTC
### Expected Behavior
When `set pen size to (1)` is called, all pen lines should be size 1

### Actual Behavior
The thickness is inconsistent

On Windows 10, Firefox 76:
![image](https://user-images.githubusercontent.com/33279053/81372612-c4d7e980-9135-11ea-9e0b-8ae8c3b81dec.png)

[Repro by hclhcl](https://scratch.mit.edu/projects/393134600/), probably taken on iOS:
![image](https://user-images.githubusercontent.com/33279053/81372664-ea64f300-9135-11ea-82fc-30f829cc686f.png)

This is a screenshot from hotfix/totally-normal-2020 branch, and it is behaving correctly:
![image](https://user-images.githubusercontent.com/33279053/81372851-53e50180-9136-11ea-95b7-20827efac37b.png)

**This may be a regression issue**

### Steps to Reproduce
Run https://scratch.mit.edu/projects/393133363/ and see

### Operating System and Browser
Windows 10 Firefox 76
hclhcl: 
My browser / operating system: MacOS Macintosh X 10.15, Safari 13.0.5, No Flash version detected

[thanks hclhcl for reporting this!](https://scratch.mit.edu/discuss/post/3993600/)

**Comment by BryceLTaylor** [comment] 2020-05-11 17:15
The size of the stage seems to affect this on mac for both chrome and firefox.  If you make the browser window small enough that the stage reduces to the smaller size, every other line disappears in that project.
![Screen Shot 2020-05-11 at 1.14.19 PM.png](https://codetreeusercontent.s3.amazonaws.com/uploads/f2abf04a-0dc0-43d9-8c27-264c89d1c4c1/Screen+Shot+2020-05-11+at+1.14.19+PM.png)

**Comment by adroitwhiz** [comment] 2020-05-11 17:16
@BryceLTaylor The resizing/small stage making lines disappear is just #565 manifesting again.

**Comment by BryceLTaylor** [comment] 2020-05-11 17:26
Also, I don't think it's an issue with the length of the line.  I believe that the position on the screen is affecting the line thickness.  I have made a remix of the project here: scratch.mit.edu/projects/394181361

In it I made all the lines draw at the same length and the same behavior is visible as it relates to line thickness.

**Comment by BryceLTaylor** [comment] 2020-05-11 17:30
I believe this is related to this issue, which is about the way that pen lines are drawn on the smaller stage: https://github.com/LLK/scratch-render/issues/565

**Comment by BryceLTaylor** [comment] 2020-05-11 17:33
It is also related to this bug, but that has to do more with stamping: https://github.com/LLK/scratch-render/issues/558

**Comment by BryceLTaylor** [comment] 2020-05-11 17:35
I think I'm just going to close this one as a duplicate of #565.  The manifestation is slightly different, but I believe they are the same root cause.

**Closed as completed by BryceLTaylor** 2020-05-11 17:35 UTC

**Comment by adroitwhiz** [comment] 2020-05-11 17:38
The pen size changing depending on the stage position on iOS is definitely a separate issue-- the pen line shader code is misbehaving. I rewrote it in #600 and a demo is up on https://adroitwhiz.github.io/scratch-gui/bryces-devices/ -- can you check if the issue is gone there?
