### ISSUE TITLE
Stamp with a sprite using ghost effect darkens the colors

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-render#110] opened 2017-03-01 20:46 UTC
### Expected Behavior

Example project: https://scratch.mit.edu/projects/147409812/#player
When ghost effect is applied to a sprite, stamps the sprite with transparency, colors otherwise unchanged.

![screen shot 2017-03-01 at 3 45 34 pm](https://cloud.githubusercontent.com/assets/399209/23480507/29dc6814-fe96-11e6-8797-5421773c9416.png)

### Actual Behavior

In the art microworld, stamping without changing the ghost effect was fine. After changing the ghost effect with a key stamping did become transparent, but the colors became darker. It looked like it was stamping shadows (grey) instead of the color of the sprite.

![screen shot 2017-03-01 at 3 41 47 pm](https://cloud.githubusercontent.com/assets/399209/23480355/a958ad74-fe95-11e6-9802-7c7beeedb5ea.png)
 
I saved the project json as well, but gh won't let me attach it.

### Steps to Reproduce

Example project: https://scratch.mit.edu/projects/147409812/#player
Forever 
point towards mouse
move 10 steps
change color effect by 10
stamp

When down arrow 
change ghost effect by 10

### Operating System and Browser

Mac OS 10.11.6 Chrome Version 56.0.2924.87 (64-bit)

**Comment by thisandagain** [comment] 2017-03-01 20:47
Thanks @chrisgarrity ! 🐞

**Comment by chrisgarrity** [comment] 2017-03-03 20:43
I think this project isn't working due to stamping with ghost as well:
https://llk.github.io/scratch-gui/#70923304

**Comment by cwillisf** [comment] 2017-04-06 23:00
Hints for anyone who would like to give this a try:
Scratch 2.0 followed the Adobe Flash convention of premultiplied alpha. Usually, half-transparent white is represented as ARGB(0.5, 1, 1, 1), but when using premultiplied alpha it's ARGB(0.5, 0.5, 0.5, 0.5). This simplifies the blending math a bit and in particular can make software blending faster. In WebGL terms, this means switching from `gl.blendFunc(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA)` ("normal" blending) to `gl.blendFunc(gl.ONE, gl.ONE_MINUS_SRC_ALPHA)`.

At first glance, the "actual behavior" image looks like what happens when you use `SRC_ALPHA, ONE_MINUS_SRC_ALPHA` blend factors with textures designed to be drawn with `ONE, ONE_MINUS_SRC_ALPHA` blend factors. Another, perhaps stronger possibility is that there's a conflict in the fragment shader between the part that premultiplies the alpha channel and the part where the ghost effect modifies the alpha channel.

Whatever the solution turns out to be, be sure to double-check that it works as expected both with lots of clones (blending to the regular back buffer) and stamping (blending to the pen layer).

**Comment by chrisgarrity** [comment] 2017-12-11 19:35
Simpler steps to reproduce:
1. Set the ghost effect to 50
2. Click stamp
3. Move the sprite
![screen shot 2017-12-11 at 2 32 06 pm](https://user-images.githubusercontent.com/399209/33849996-63e7e022-de80-11e7-863c-7ac064a5858e.png)

The circle on the left is the 'stamp' the circle on the right is the sprite being stamped.

**Comment by Mr-Dave2** [comment] 2018-07-25 17:18
I'v added another instance of this problem because it was reported [here ](https://scratch.mit.edu/discuss/topic/299791/?page=239#post-3183043) by user welfringer and it is caused by using clones (which I think was mentioned as something to double-check).  ![dark stamped clones](https://user-images.githubusercontent.com/35544966/43215589-2b50c704-9002-11e8-8309-3ea9eaa9620e.gif)

The Scratch 2 link is [here](https://scratch.mit.edu/projects/235989645/).  Scratch 3 link is [here](https://preview.scratch.mit.edu/#235989645)

Windows 7, Firefox 61.0.1 and Chrome Version 67.0.3396.99 (Official Build) (64-bit)

**Comment by gnarf** [comment] 2018-08-02 16:29
This will be fixed with https://github.com/LLK/scratch-render/pull/319 - We noticed this when rewriting pen stamp - it resulted in "Emo Bob Ross":
![2018-07-31 15 53 05](https://user-images.githubusercontent.com/549355/43597278-a248cd7c-964f-11e8-850f-097d507ee69a.gif)

**Closed** 2018-08-08 18:30 UTC
Labels: bug, needs-triage
