### ISSUE TITLE
Background offset on this project

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-render#238] opened 2018-01-27 21:01 UTC
### Expected Behavior

_Please describe what should happen_

https://scratch.mit.edu/projects/196409381/#editor
![image](https://user-images.githubusercontent.com/654102/35476273-148fa454-037b-11e8-9eb6-47b5b70e69fc.png)

### Actual Behavior

_Describe what actually happens_

https://llk.github.io/scratch-gui/develop/#196409381
![image](https://user-images.githubusercontent.com/654102/35476276-1a0a5b72-037b-11e8-8382-64dcb755136d.png)

To be specific, the backdrop gets rendered offset. I'm not sure if this is at all related to any of the offset issues @fsih and @cwillisf have been dealing with recently, because this is specifically offset in the rendering.

**Comment by towerofnix** [comment] 2018-11-16 15:34
Can't reproduce this. Potentially fixed by LLK/scratch-vm#1164.

**Closed** 2018-11-16 16:15 UTC
Labels: bug, compatibility, help wanted
