### ISSUE TITLE
Stage blank on Safari (OSX, IPhone)

### ISSUE THREAD

**Issue by gengshenghong** [LLK/scratch-render#148] opened 2017-06-30 03:39 UTC
### Expected Behavior
Stage should work (display the cat) when open https://llk.github.io/scratch-gui/ or https://llk.github.io/scratch-vm/

### Actual Behavior
The stage is just blank. When I test scratch-gui or scratch-vm on my Mac and iOS (various versions I've tried), the stage is just empty, the cat is not shown.
On my Mac, it works in Chrome (when I enabled software rendering list options). I've enabled webgl in Safari, but still blank. Also, I've checked the console of Safari browser, **no errors at all**. I've no idea as it does not even show an error message...
Also, I've tested webgl support using:
https://get.webgl.org/, it works for the cube.
https://www.contextis.com//files/blog-WebGL-webgltest.html, it tell me my Safari has full webgl support and unsafe....
What is missing then? Is this expected?

### Steps to Reproduce
Open the browser and open the link, check the stage.

### Operating System and Browser
Mac OS 10.11.6 Safari 10.1.1
iOS (iphone 6 and above, I've tested several), Safari and Chrome (latest from app store)

**Comment by liam4** [comment] 2017-06-30 11:31
One thing I'd like to note: it might be worth taking a look at http://llk.github.io/scratch-render/ to see how things behave there. It's a more isolated playground for experimenting with the Scratch 3.0 renderer. It might help see if the problem is in the renderer (e.g. Safari isn't handling WebGL correctly) or in the GUI (e.g. the GUI failed to attach the renderer in Safari).

---

https://llk.github.io/scratch-gui/ behaves similarly for me: there is nothing in the stage area. But it may also be worth noting that the sprite palette doesn't display, either:

![Screenshot showing lack of sprite palette](https://user-images.githubusercontent.com/9948030/27733618-6aefe7a0-5d6d-11e7-91a5-744ea9180caf.png)

The scripting area works mostly as you'd expect it to (and it's of course outside the scope of this issue, anyways). There are no error logs.

https://llk.github.io/scratch-gui/develop/ (the latest build) runs identically, but the stage seems to load and is filled with black this time:

![Screenshot showing stage filled with black (and lack of sprite palette)](https://user-images.githubusercontent.com/9948030/27733656-a8208ba2-5d6d-11e7-97ed-84c4b2a123e6.png)

I wouldn't really know if this means that it got further (e.g. if canvas is default white, but was filled by black by WebGL) or less far (e.g. if canvas was filled black by WebGL, but is supposed to display as white, which non-develop succeeded at).

One thing to note is that in the development version I do get some error logs: "TypeError: Not enough arguments", in `decodeAudioData`/`onload` (dist.js:563). That's not too surprising since work on the audio setup *has* been done recently.

**Comment by gengshenghong** [comment] 2017-06-30 16:33
@liam4 Thank you for your information. I've tested the render playground and confirmed it is not an issue of scratch render, it works quite well! So, this seems an bug in scratch gui to attach the webgl context. This issue should be moved to scratch gui, I've submit a new one. Thanks.

**Comment by rschamp** [comment] 2017-07-28 15:20
Fixed in https://github.com/LLK/scratch-gui/pull/543

**Comment by thisandagain** [comment] 2017-07-28 15:24
LLK/scratch-gui#543 was closed but not merged.

**Comment by xmeow** [comment] 2017-08-03 10:46
This also happens on some laptops with dual graphic card. 
![image](https://user-images.githubusercontent.com/3390845/28918443-dfb0e08e-787b-11e7-834a-3574ef009ba1.png)

If open chrome://gpu may find Rasterization is software only.

**Comment by paulkaplan** [comment] 2017-12-05 19:52
Because the stage now renders when using iOS, I'm going to close this issue.

**Closed by paulkaplan** 2017-12-05 19:52 UTC
Labels: bug
