### ISSUE TITLE
Creating clones and deleting them crashes Scratch

### ISSUE THREAD

**Issue by filips123** [LLK/scratch-render#530] opened 2019-11-29 10:06 UTC
### Expected Behavior

Scratch should not crash.

### Actual Behavior

Scratch crashes.

### Steps to Reproduce

Create a project that creates clone of a sprite. After clone is created, it creates another clone and deletes itself. After running, Scratch will crash.

I created example project [here](https://scratch.mit.edu/projects/349369279/).

### Operating System and Browser

* Chrome 78 on Windows 10
* Edge on Windows 10

**Comment by apple502j** [comment] 2019-11-29 13:28
Duplicate of LLK/scratch-vm#2282

**Closed** 2019-12-04 15:37 UTC
